### ISSUE TITLE
Notification Queue ArrayIndexOutOfBoundsException Exception

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#100]
_Original author: Eventl...@gmail.com (January 16, 2012 23:04:08)_

The following is the detailed exception logged. The reported out of range index keeps on increasing if more payloads are added to the queue.

1-16-2012 15:19:34 com.nyx.utility.logging.FileLogger exception
SEVERE: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 16
                at java.util.Vector.get(Vector.java:721)
                at javapns.notification.transmission.NotificationThreads.getNextThread(NotificationThreads.java:194)
                at javapns.notification.transmission.NotificationThreads.getNextAvailableThread(NotificationThreads.java:180)
                at javapns.notification.transmission.NotificationThreads.add(NotificationThreads.java:167)
                at javapns.notification.transmission.NotificationThreads.add(NotificationThreads.java:156)
                at com.eventloud.server.common.processing.util.UPNS.push(UPNS.java:77)
                at com.eventloud.server.common.processing.db.User.pushMessage(User.java:242)
                at com.eventloud.server.common.processing.db.VenueLoop.pushNotification(VenueLoop.java:137)
                at com.eventloud.server.event.processing.db.EventVenueLoop.sendNotification(EventVenueLoop.java:69)
                at com.eventloud.server.event.processing.util.UEvent.postEvent(UEvent.java:129)
                at com.eventloud.server.event.processing.processor.PEventPost.processRequest(PEventPost.java:69)
                at com.eventloud.server.event.processing.processor.PEventPost.processRequest(PEventPost.java:1)
                at com.eventloud.server.common.processing.processor.PUser.processRequest(PUser.java:43)
                at com.eventloud.server.common.processing.processor.PUser.processRequest(PUser.java:1)
                at com.eventloud.server.common.processing.processor.PConsumer.processMessage(PConsumer.java:31)
                at com.eventloud.server.common.processing.processor.PConsumer.processMessage(PConsumer.java:1)
                at com.nyx.core.structure.processor.LoggedProcessor.doProcess(LoggedProcessor.java:54)
                at com.nyx.core.structure.AbstractProcessor.process(AbstractProcessor.java:66)
                at com.nyx.core.structure.protocol.RProtocol$ProcessorTask.execute(RProtocol.java:247)
                at com.nyx.core.execution.EventExecutable.doExecute(EventExecutable.java:80)
                at com.nyx.core.execution.Executable.execute(Executable.java:81)
                at com.nyx.core.execution.EventExecutable.executeAwait(EventExecutable.java:159)
                at com.nyx.core.structure.protocol.RProtocol.handle(RProtocol.java:147)
                at com.nyx.core.structure.channel.util.Dispatcher$RNotificationTask.execute(Dispatcher.java:486)
                at com.nyx.core.execution.EventExecutable.doExecute(EventExecutable.java:80)
                at com.nyx.core.execution.Executable.execute(Executable.java:81)
                at com.nyx.core.execution.AssistExecutor.run(AssistExecutor.java:107)
                at java.lang.Thread.run(Thread.java:636)

1-16-2012 15:19:34 com.nyx.utility.logging.FileLogger severe
SEVERE: Sending push notification failed.

_Original issue: http://code.google.com/p/javapns/issues/detail?id=100_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on January 16, 2012 23:09:41_
Which version of the library are you using?  This looks like a older bug which is already fixed.

**Comment by mwkirk** [comment]
_From Eventl...@gmail.com on January 16, 2012 23:18:18_
I'm using version 2.1.

**Comment by mwkirk** [comment]
_This issue is a duplicate of #85_
