### ISSUE TITLE
Problems while sending push-message to production APNS server

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#128]
_Original author: jha.vks...@googlemail.com (June 19, 2012 15:45:47)_

When I am trying to send message to  Apple sandbox it works fine every time;
However while I am switching to live with production certificate I am getting  error.
This the version of APNS software I am using:

```
      &lt;groupId&gt;com.notnoop.apns&lt;/groupId&gt;
        &lt;artifactId&gt;apns&lt;/artifactId&gt;
        &lt;version&gt;0.1.6&lt;/version&gt;
```

We have deployed our app on Unix box.
Here is the error:
log4j:throwable&gt;&lt;![CDATA[java.net.SocketException: Connection closed by remote host
       at com.sun.net.ssl.internal.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1269)
       at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:43)
       at java.io.OutputStream.write(OutputStream.java:58)
       at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:161)
       at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
       at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:52)
       at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
       at com.bskyb.interactive.mobile.jms.PushMessageQueueListener.messageReceived(PushMessageQueueListener.java:73)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
       at 

Is it a cert problem not sure

_Original issue: http://code.google.com/p/javapns/issues/detail?id=128_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on July 02, 2012 21:20:10_
You are not using JavaPNS, so I am closing this issue.
