### ISSUE TITLE
OutOfMemoryError when remote host closed connection

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#144]
_Original author: m...@felixschulze.de (September 18, 2012 07:33:09)_

I get OutOfMemoryError exceptions when the apple push server is not reachable.

If apple is reachable everything works.

Any ideas?

2012-09-17 22:51:54,763 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:51:58,590 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:51:58,591 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:52:00,908 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:52:00,908 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:52:00,908 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:52:53,555 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:52:55,789 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:53:00,311 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:53:11,883 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:54:08,263 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:54:25,541 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:54:32,390 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:54:50,758 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:55:03,120 ERROR: javapns.notification.PushNotificationManager - Attempt to send Notification failed and beyond the maximum number of attempts permitted
2012-09-17 22:55:10,197 ERROR: javapns.notification.PushNotificationManager - Attempt to send Notification failed and beyond the maximum number of attempts permitted
2012-09-17 22:55:20,035 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
2012-09-17 22:57:20,157 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
Exception in thread &quot;JavaPNS grouped notification thread in LIST mode&quot; java.lang.OutOfMemoryError: Java heap space
2012-09-17 22:58:15,277 ERROR: javapns.notification.PushNotificationManager - Attempt to send Notification failed and beyond the maximum number of attempts permitted
2012-09-17 22:58:17,485 INFO : javapns.notification.PushNotificationManager - Attempt failed (Remote host closed connection during handshake)... trying again
Exception in thread &quot;JavaPNS grouped notification thread in LIST mode&quot; java.lang.OutOfMemoryError: Java heap space
    at sun.security.ssl.InputRecord.&lt;init&gt;(InputRecord.java:84)
    at sun.security.ssl.AppInputStream.&lt;init&gt;(AppInputStream.java:50)
    at sun.security.ssl.SSLSocketImpl.init(SSLSocketImpl.java:552)
    at sun.security.ssl.SSLSocketImpl.&lt;init&gt;(SSLSocketImpl.java:383)
    at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:90)
    at javapns.communication.ConnectionToAppleServer.getSSLSocket(ConnectionToAppleServer.java:155)
    at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:440)
    at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:350)
    at javapns.notification.transmission.NotificationThread.runList(NotificationThread.java:230)
    at javapns.notification.transmission.NotificationThread.run(NotificationThread.java:201)
    at java.lang.Thread.run(Thread.java:679)

_Original issue: http://code.google.com/p/javapns/issues/detail?id=144_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 22, 2012 13:52:11_
How much memory have you allocated to your program?  And for how long was the thread running before it threw an OutOfMemoryError?

It could be related to issue #120...

**Comment by mwkirk** [comment]
_From m...@felixschulze.de on September 22, 2012 18:37:04_
1024MB.
Runs about 3 hours (the complete application)
