### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#159]
_Original author: stemp...@puzzle.ch (December 10, 2012 12:41:22)_

<b>What steps will reproduce the problem?</b>
I can't really reproduce it, but when we have to send a lot of push notifications several 1000's) this exception occured.

<b>What version of the product are you using? On what operating system?</b>
2.2

Exception in thread &quot;JavaPNS grouped notification thread in LIST mode&quot; java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.BufferedReader.&lt;init&gt;(BufferedReader.java:80)
        at java.io.BufferedReader.&lt;init&gt;(BufferedReader.java:91)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:389)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:350)
        at javapns.notification.transmission.NotificationThread.runList(NotificationThread.java:228)
        at javapns.notification.transmission.NotificationThread.run(NotificationThread.java:199)
        at java.lang.Thread.run(Thread.java:619)
Exception in thread &quot;JavaPNS grouped notification thread in LIST mode&quot; java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3209)
        at java.lang.String.&lt;init&gt;(String.java:215)
        at java.lang.StringBuffer.toString(StringBuffer.java:585)
        at org.json.JSONObject.toString(JSONObject.java:1304)
        at javapns.notification.Payload.toString(Payload.java:110)
        at javapns.notification.PushNotificationPayload.verifyPayloadIsNotEmpty(PushNotificationPayload.java:353)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:367)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:350)
        at javapns.notification.transmission.NotificationThread.runList(NotificationThread.java:228)
        at javapns.notification.transmission.NotificationThread.run(NotificationThread.java:199)
        at java.lang.Thread.run(Thread.java:619)
Exception in thread &quot;JavaPNS grouped notification thread in LIST mode&quot; java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.BufferedReader.&lt;init&gt;(BufferedReader.java:80)
        at java.io.BufferedReader.&lt;init&gt;(BufferedReader.java:91)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:389)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:350)
        at javapns.notification.transmission.NotificationThread.runList(NotificationThread.java:228)
        at javapns.notification.transmission.NotificationThread.run(NotificationThread.java:199)
        at java.lang.Thread.run(Thread.java:619)
Exception in thread &quot;JavaPNS grouped notification thread in LIST mode&quot; java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.BufferedReader.&lt;init&gt;(BufferedReader.java:80)
        at java.io.BufferedReader.&lt;init&gt;(BufferedReader.java:91)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:389)
        at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:350)
        at javapns.notification.transmission.NotificationThread.runList(NotificationThread.java:228)
        at javapns.notification.transmission.NotificationThread.run(NotificationThread.java:199)
        at java.lang.Thread.run(Thread.java:619)

_Original issue: http://code.google.com/p/javapns/issues/detail?id=159_

**Comment by mwkirk** [comment]
_From stemp...@puzzle.ch on January 30, 2013 07:12:05_
Did somebody already take a look at this issue?  Will a new version be released soon?
