### ISSUE TITLE
Key Store exception while pushing the notification

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#163]
_Original author: mani.ala...@gmail.com (January 24, 2013 10:33:02)_

<b>What steps will reproduce the problem?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>
Javapns-2.2 and bcprov-jdk15-146 

<b>Please provide any additional information below.</b>

We are facing issue while pushing the Apple notifications.
Could you please provide some information on how to resolve this issue.

We are able to push the notifications successfully with the standalone program by using the same certificate and the same server.

Below is the exception we are getting while pushing the notifications after integrating the code with schedulers.

|javapns.communication.exceptions.KeystoreException||Keystore exception: exception unwrapping private key - java.security.InvalidKeyException: Illegal key size||Stack Trace : javapns.communication.exceptions.KeystoreException: Keystore exception: exception unwrapping private key - java.security.InvalidKeyException: Illegal key size
        at javapns.communication.KeystoreManager.wrapKeystoreException(KeystoreManager.java:178)
        at javapns.communication.KeystoreManager.loadKeystore(KeystoreManager.java:66)
        at javapns.communication.KeystoreManager.loadKeystore(KeystoreManager.java:42)
        at javapns.communication.KeystoreManager.loadKeystore(KeystoreManager.java:29)
        at javapns.communication.ConnectionToAppleServer.&lt;init&gt;(ConnectionToAppleServer.java:54)
        at javapns.notification.ConnectionToNotificationServer.&lt;init&gt;(ConnectionToNotificationServer.java:16)
        at javapns.notification.PushNotificationManager.initializeConnection(PushNotificationManager.java:105)
        at javapns.Push.sendPayload(Push.java:171)
        at javapns.Push.combined(Push.java:100)
        at com.scheduler.managedtask.helper.PushNotificationHelper.pushSevereAlerts(Unknown Source)
        at com.scheduler.managedtask.helper.PushNotificationHelper.pushNotification(Unknown Source)
        at com.scheduler.managedtask.SeverePushNotificationTask.pushNotifications(SeverePushNotificationTask.java:58)
        at com.scheduler.managedtask.SeverePushNotificationTask.execute(SeverePushNotificationTask.java:44)
        at com.scheduler.scheduledtask.IterativeManagedTaskAdaptor.process(IterativeManagedTaskAdaptor.java:201)
        at livexp.coreimpl.asal.FluxActionListenerAdaptor.actionFired(FluxActionListenerAdaptor.java:47)
        at fluximpl.JavaActionImpl.a(JavaActionImpl.java:0)
        at fluximpl.p8.a(p8.java:641)
        at fluximpl.p8.b(p8.java:565)
        at fluximpl.p8.a(p8.java:353)
        at fluximpl.m9.d(m9.java:23)
        at fluximpl.o2c.run(o2c.java:10)
Caused by: java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: Illegal key size
        at org.bouncycastle.jce.provider.JDKPKCS12KeyStore.unwrapKey(Unknown Source)
        at org.bouncycastle.jce.provider.JDKPKCS12KeyStore.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1150)
        at javapns.communication.KeystoreManager.loadKeystore(KeystoreManager.java:64)

_Original issue: http://code.google.com/p/javapns/issues/detail?id=163_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on February 05, 2013 19:33:58_
Do you still have that exception?

**Comment by mwkirk** [comment]
_From mani.ala...@gmail.com on February 06, 2013 06:00:25_
Hi,

Yes, we are still facing that exception.

**Comment by mwkirk** [comment]
_From sype...@gmail.com on February 07, 2013 00:06:06_
The following page seems to provide quite a lot of information related to your particular exception:

http://stackoverflow.com/questions/6363801/invalidkeyexception-illegal-key-size-java-code-throwing-exception-for-encryp

Also, are you by any chance using "" (blank string) as a password for the keystore?

If nothing helps, could you please attach a copy of your source code?

Thank you!

**Comment by mwkirk** [comment]
_From sype...@gmail.com on March 01, 2013 17:18:44_
Closing for lack of feedback from original poster.
