### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#164]
_Original author: stack.b...@gmail.com (January 31, 2013 23:08:27)_

<b>What steps will reproduce the problem?</b>
1. create pushQueue with numThread = 1
2. send 20 messages in a for-loop (in a burst)

<b>What is the expected output? What do you see instead?</b>
I expect all 20 messaged to be sent to the device.
However, I am seeing the following error (it can happen at anywhere from right after first message to right before 20th message)

java.util.ConcurrentModificationException
    at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)
    at java.util.AbstractList$Itr.next(AbstractList.java:343)
    at com.neimanmarcus.apns.wsclient.APNSWSClient.sendMessage(APNSWSClient.java:87)
    at com.neimanmarcus.apns.controller.impl.APNSControllerImpl.sendAPNS(APNSControllerImpl.java:47)
    at com.neimanmarcus.apns.services.impl.APNSServiceImpl.sendMessage(APNSServiceImpl.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:669)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:574)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:680)

<b>What version of the product are you using? On what operating system?</b>
2.2

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/javapns/issues/detail?id=164_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on February 05, 2013 19:17:00_
Could you please provide the code that is throwing this exception?  Without it, it's pretty much impossible to know what is going on...  Thank you.

**Comment by mwkirk** [comment]
_From sype...@gmail.com on March 01, 2013 17:18:28_
Closing for lack of feedback from original poster.
