### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#165]
_Original author: johannes...@gmail.com (February 07, 2013 15:33:53)_

<b>What steps will reproduce the problem?</b>
1. Create your .p12 file according to Apple´s workflow
2. Take the Java class found in wiki: http://code.google.com/p/javapns/wiki/ManagingPushErrors 
3. Run with JDK 1.6 - Works correct!
4. Change JDK to 1.7 - Does not work.

<b>What is the expected output? What do you see instead?</b>
Expected a &quot;Push notification sent successfully to....&quot; But got: 

javapns.communication.exceptions.InvalidCertificateChainException: Invalid certificate chain (Received fatal alert: certificate_unknown)!  Verify that the keystore you provided was produced according to specs...
    at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:410)
    at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:350)
    at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:320)
    at javapns.Push.sendPayload(Push.java:177)
    at javapns.Push.alert(Push.java:47)
    at my.test.JavapnsTest.main(JavapnsTest.java:17)

<b>What version of the product are you using? On what operating system?</b>
Javapns 2.2. with OSX10.8.2 

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/javapns/issues/detail?id=165_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on February 07, 2013 16:02:20_
Indeed, the documented requirements indicates that there are problems with SSL connections under Java 7.

**Comment by mwkirk** [comment]
_From johannes...@gmail.com on February 08, 2013 05:44:54_
Yes, I have read the documentation. However since both Java 5 and 6 reached EOL and therefore, in the best of worlds, shouldn't be used, I raised this issue to see if anyone did come up with a solution to this problem. Anyone?
