### ISSUE TITLE
toDerInputStream rejects tag 66

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#26]
_Original author: leclere....@gmail.com (August 25, 2010 09:38:03)_

<b>What steps will reproduce the problem?</b>
The error occured when I try to initialize the ssl connection :
1. pushManager.initializeConnection(PushNotification.HOST, PushNotification.PORT, PushNotification.CERTIFICATE, PushNotification.PASSWORD, SSLConnectionHelper.KEYSTORE_TYPE_PKCS12);

I test also with the classical approach
2. KeyStore ks=KeyStore.getInstance(&quot;pkcs12&quot;);
3. ks.load(new FileInputStream(&quot;C:/key.pem&quot;),&quot;password&quot;.toCharArray());

Always I catch the same error :

java.io.IOException: toDerInputStream rejects tag type 66
    at sun.security.util.DerValue.toDerInputStream(Unknown Source)
    at com.sun.net.ssl.internal.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
    at java.security.KeyStore.load(Unknown Source)

I test on Windows (Eclipse) and Debian (jboss server) ...

What to do please ?

_Original issue: http://code.google.com/p/javapns/issues/detail?id=26_

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on August 27, 2010 02:49:17_
Have you gone thru the steps on:
http://code.google.com/p/javapns/wiki/GetAPNSCertificate

and:
http://code.google.com/p/javapns/wiki/Tips

my guess is the pem file is bad (unknown Source)

**Comment by mwkirk** [comment]
_From leclere....@gmail.com on August 27, 2010 07:08:55_
I have found what was going wrong : the certificate was in PEM format but in JAVA I must read the .p12 file generated by xcode and the keytool chain.

Thanks for your answers.
