### ISSUE TITLE
Client already exists

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#28]
_Original author: bzn...@gmail.com (September 29, 2010 14:29:42)_

<b>What steps will reproduce the problem?</b>
1. I'm running this code in ActiveMatrix as a service
2. When i call the service it states that Client already exists.
3. It appears to be hanging onto the manager  instance. is there a way to destroy the instance  before it tires to create it?

<b>What is the expected output? What do you see instead?</b>
If I run the code as a stand alone program it works fine. 
<b>What version of the product are you using? On what operating system?</b>
Java APNS 1..5-v1.6.2

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/javapns/issues/detail?id=28_

**Comment by mwkirk** [comment]
_From saggamma...@gmail.com on October 04, 2010 11:54:40_
i am also facing same pb....

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on October 05, 2010 04:51:55_
What is ActiveMatrix?

How is the lib being instantiated?

**Comment by mwkirk** [comment]
_From pankajav...@gmail.com on November 24, 2010 21:29:43_
The Solution for this is very simple just remove the device after sending the notification  pushManager.removeDevice();

**Comment by mwkirk** [comment]
_From sguerr...@gmail.com on July 29, 2011 02:45:43_
Hello,

Your solution is as follows:
The Solution for this is very simple just remove the device after sending the notification  pushManager.removeDevice(); 

Where does this need to be called.... in the main, when i call it there i get the follwoing error:
Removing Token from Device [aebf53cc8d6bfaf4eb91a389c5a3f1ab91fa5b0fc83746a14b....]

Unknown client
    at ts.javapns.back.DeviceFactory.removeDevice(DeviceFactory.java:118)
    at ts.javapns.back.PushNotificationManager.removeDevice(PushNotificationManager.java:199)
    at org.apache.jsp.japnslist_jsp._jspService(org.apache.jsp.japnslist_jsp:144)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:322)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:291)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:241)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:744)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Unknown Source)

Please help

Sergio

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 06, 2011 16:29:31_
Your code always adds devices with the same ID ("iPhone" in your case).  Thus if you call your Push method twice, you will indeed get a duplicate device exception (ie "Client already exists").

SOLUTION FOR JAVAPNS 1.x:  You should make sure that devices are added with unique IDs.  Using the device token as the ID is a good way of ensuring unique IDs:  pushManager.addDevice(iPhoneId, iPhoneId);    and then later:  Device client = pushManager.getDevice(iPhoneId);

SOLUTION FOR JAVAPNS 2.0:  In 2.0, there is no need to add and get devices when no persistence backend is required.  The simple "javapns.Push" class allows you to push notifications with a single line of code (see wiki).
