### ISSUE TITLE
Null pointer exception when sending message: server on linux environment

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#29]
_Original author: gauta...@gmail.com (September 29, 2010 21:49:25)_

If I use this code on a Mac, it works fine. But, if my server is running on a linux environment, it throws a null pointer exception the first time I try to send the message:
java.lang.NullPointerException
    at javapns.back.PushNotificationManager.sendNotification(Unknown Source)

After I get this exception, if I try to send a message again, I get the following error:
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1611)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1574)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1557)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1483)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:83)
    at java.io.OutputStream.write(OutputStream.java:75)
    at javapns.back.PushNotificationManager.sendNotification(Unknown Source)

Any pointers? Do I need to convert the certificate from the P12 format to some other format in linux?

Thanks,
Gautam 

_Original issue: http://code.google.com/p/javapns/issues/detail?id=29_

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on October 05, 2010 04:54:10_
I have not had an issue with the cert on linux or mac.

Are you running the latest apns lib? The old one required the apple cert to be pre-installed. The new lib will handle that for you.

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 07, 2011 13:07:16_
Old issue with no recent update, which is most likely fixed by all the reliability improvements of latest versions.  Please feel free to re-open if the issue is still valid.
