### ISSUE TITLE
Given final block not properly padded exception on initializeConnection

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#40]
_Original author: lech.mig...@gmail.com (January 14, 2011 16:07:02)_

<b>What steps will reproduce the problem?</b>

While trying to initializeConnection on the PushManager, I get the following exception:

java.io.IOException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
    at com.sun.net.ssl.internal.ssl.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1275)
    at java.security.KeyStore.load(KeyStore.java:1150)
    at javapns.back.SSLConnectionHelper.&lt;init&gt;(Unknown Source)
    at javapns.back.PushNotificationManager.initializeConnection(Unknown Source)

The password is correct as I've verified it with openssl.

<b>What is the expected output? What do you see instead?</b>

I would love to see the connection initialized :)

<b>What version of the product are you using? On what operating system?</b>

javapns 1.6.2 jdk1.5, windows XP, trying to run it from the JUnit test at this moment...

_Original issue: http://code.google.com/p/javapns/issues/detail?id=40_

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on January 19, 2011 22:15:28_
Sounds like the SSL certificate isn't loading properly... what happens when you enable ssl certificate logging as per:
http://code.google.com/p/javapns/wiki/Tips

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 07, 2011 15:39:26_
Error is typical of a keystore password issue, and is actually reported as such in javapns 2.0.  Old issue with no recent update, so closing.  Please feel free to re-open if the issue is still valid.
