### ISSUE TITLE
Unable to connect to the APNS. 

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#49]
_Original author: arulmala...@gmail.com (May 09, 2011 13:37:10)_

<b>What steps will reproduce the problem?</b>
1. Executing the same code from the Java environment
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Connected to the APNS

<b>What version of the product are you using? On what operating system?</b>
The current version of the product on Windows XP operating system

<b>Please provide any additional information below.</b>
Have been receiving the following error:
java.net.ConnectException: Connection timed out: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:520)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:545)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.&lt;init&gt;(SSLSocketImpl.java:348)
        at com.sun.net.ssl.internal.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:69)
        at javapns.back.SSLConnectionHelper.getSSLSocket(Unknown Source)
        at javapns.back.PushNotificationManager.initializeConnection(Unknown Source)
        at com.homedepot.pushnotif.PushServlet.doPost(PushServlet.java:79)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at com.homedepot.ta.aa.dao.catalina.THDDAOValve.invoke(THDDAOValve.java:811)
        at com.homedepot.ta.aa.catalina.realm.THDSingleSignOn.invoke(THDSingleSignOn.java:473)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:852)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:595)

_Original issue: http://code.google.com/p/javapns/issues/detail?id=49_

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on May 11, 2011 22:58:33_
Connection Timed Out.... seems like a firewall issue. what does the debugging say?

**Comment by mwkirk** [comment]
_From arulmala...@gmail.com on May 12, 2011 14:23:23_
Not sure if this is a firewall issue..tried the same from home and office network, and getting the same connection timed out exception.

Here is what we do

public class Constants {
// APNs Server Host & port
public static String HOST = "gateway.sandbox.push.apple.com";
public static int PORT = 2195;
public static String CERTIFICATE = "local cert path";
public static String PASSWWORD = "password";
public static String DEVICE = "iPhone";
public static String SOUND = "default";
public static int BADGE = 66;
}

pushManager.initializeConnection(Constants.HOST, Constants.PORT, Constants.CERTIFICATE, Constants.PASSWWORD,
SSLConnectionHelper.KEYSTORE_TYPE_PKCS12);

**Comment by mwkirk** [comment]
_From idb...@pugetworks.com on May 16, 2011 16:26:29_
what does the debugging output say?

http://code.google.com/p/javapns/wiki/Tips

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 07, 2011 15:46:33_
arulmalar.t, were you able to solve the connection issue you reported?  If so, could you elaborate on what was the problem and how you solved it?  May we close the issue as fixed?

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 14, 2011 15:53:42_
Issue suspected of being caused by user-specific network environment / configuration.

Closing issue as no feedback was received since issue was reported.  
Please feel free to re-open if the issue is still valid.
