### ISSUE TITLE
javax.crypto.BadPaddingException: Given final block not properly padded

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#50]
_Original author: chenguan...@163.com (May 24, 2011 06:59:50)_

java.io.IOException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
    at com.sun.net.ssl.internal.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1277)
    at java.security.KeyStore.load(KeyStore.java:1185)
    at javapns.back.SSLConnectionHelper.&lt;init&gt;(Unknown Source)
    at javapns.back.PushNotificationManager.initializeConnection(Unknown Source)
    at cn.knet.wlb2b.ws.PushNotification.main(PushNotification.java:44)
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
    at com.sun.crypto.provider.SunJCE_f.b(DashoA13_..)
    at com.sun.crypto.provider.SunJCE_f.b(DashoA13_..)
    at com.sun.crypto.provider.PKCS12PBECipherCore.b(DashoA13_..)
    at com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndRC2_40.engineDoFinal(DashoA13_..)
    at javax.crypto.Cipher.doFinal(DashoA13*..)
    at com.sun.net.ssl.internal.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1274)
    ... 4 more

_Original issue: http://code.google.com/p/javapns/issues/detail?id=50_

**Comment by mwkirk** [comment]
_From idb...@pugetworks.com on May 24, 2011 21:10:48_
Something is wrong with your cert.

Where are you storing the cert? In what format? How did it get there? etc....

**Comment by mwkirk** [comment]
_From bda...@gmail.com on August 03, 2011 06:05:19_
Same problem here.  It worked fine on a different machine, so I'm not sure what's wrong.

I'm storing the certificate as a file, "testcert.p12".  I emailed it to myself from the machine I made it on (Keychain app -> select developer and push cert, export).  I've re-made and re-emailed it to myself so I don't think it was a transmission error.  I'm working with Eclipse Helios on a Windows 7 machine, with JDK 1.5.

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on August 03, 2011 14:43:38_
I assume you are using the jdk 1.5 version.

Sounds like the SSL certificate isn't loading properly... what happens when you enable ssl certificate logging as per:
http://code.google.com/p/javapns/wiki/Tips

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on August 03, 2011 17:10:38_
You say you 'emailed it to myself'...

Are you sure the file didn't get binhex encoded or modified in transit?

Does the filesize match on the originating machine and target machine?

Can you find a better way to copy the file? ftp? winscp? sneakernet?

Can you verify that java can load the file at all?

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 07, 2011 15:47:43_
bdares, were you able to solve the issue you reported?  Was it related to your keystore format or password?  May we close this issue as fixed?  Thank you!

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 14, 2011 16:00:04_
Issue suspected of being caused by invalid password for given keystore.

Closing issue as no feedback was received by original poster since issue was reported.  
Please feel free to re-open if the issue is still valid.

**Comment by mwkirk** [comment]
_From ambitiou...@gmail.com on October 19, 2011 07:35:24_
if we wanna decrypt a encrypted file than this exception arise (file is encrypted). 
but if we encrypt file n thank decrypt in same code thank code execute successfully

can some help me please

**Comment by mwkirk** [comment]
_From sype...@gmail.com on October 19, 2011 14:34:09_
I do not understand what you mean.  Please provide a copy of the code you are trying to run, and the exception (with stack trace) you are getting.  Thank you.

**Comment by mwkirk** [comment]
_From digitech...@gmail.com on November 23, 2011 11:46:35_
    public static void main(String[] args) throws Exception {
        InputStream in = new FileInputStream(new File("C:/user.p12"));
        KeyStore ks = java.security.KeyStore.getInstance("PKCS12");
        ks.load(in,"user".toCharArray());
        in.close();
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        tmf.init(ks);
        X509TrustManager defaultTrustManager = (X509TrustManager)tmf.getTrustManagers()[0];
        SSLContext context =SSLContext.getInstance("TLS");
        context.init(null, new TrustManager[]{defaultTrustManager}, null);
        SSLSocketFactory sslSocketFactory = context.getSocketFactory();

```
    URL url = new URL("https://192.168.1.1:8443/test/test");
    URLConnection conn = url.openConnection();
    ((HttpsURLConnection) conn).setHostnameVerifier(new javax.net.ssl.HostnameVerifier() {


        @Override
        public boolean verify(String arg0, SSLSession arg1) {
            // TODO Auto-generated method stub
            return true;
        }
    });
    ((HttpsURLConnection)conn).setSSLSocketFactory(sslSocketFactory);
    conn.connect();
```

I configure my tomcat using server.p12  , I get the following error

Exception in thread "main" java.io.IOException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
    at com.sun.net.ssl.internal.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
    at java.security.KeyStore.load(Unknown Source)
    at testpack.Newtest.main(Newtest.java:24)
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
    at com.sun.crypto.provider.SunJCE_f.b(DashoA13_..)
    at com.sun.crypto.provider.SunJCE_f.b(DashoA13_..)
    at com.sun.crypto.provider.PKCS12PBECipherCore.b(DashoA13_..)
    at com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndRC2_40.engineDoFinal(DashoA13_..)
    at javax.crypto.Cipher.doFinal(DashoA13*..)
    ... 3 more

**Comment by mwkirk** [comment]
_From sype...@gmail.com on November 23, 2011 14:01:37_
Your code is not even using the JavaPNS library...  Are you requesting support in a project you are not using?  Or am I missing something here...
