### ISSUE TITLE
manager.sendNotification("1","...") index out of range exception

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#51]
_Original author: Austin.France (May 24, 2011 15:14:55)_

<b>What steps will reproduce the problem?</b>
1. pass a device token of uneven length to manager.sendNotification()

<b>What is the expected output? What do you see instead?</b>

to throw and invalid argument exception or invalid device token exception (or perhaps UnknownDeviceToken exception), instead it throws and index out of range exception which doesn't really give a clue as to what is wrong.

<b>What version of the product are you using? On what operating system?</b>

Revision 152
OSX

<b>Please provide any additional information below.</b>

java.lang.StringIndexOutOfBoundsException: String index out of range: 2
    at java.lang.String.substring(String.java:1934)
    at javapns.back.PushNotificationManager.getMessage(PushNotificationManager.java:251)
    at javapns.back.PushNotificationManager.sendNotification(PushNotificationManager.java:131)
    at com.redskyit.apns.processors.NotificatonProcessor.send(NotificatonProcessor.java:223)
    at com.redskyit.apns.processors.NotificatonProcessor.process_NOTIFY(NotificatonProcessor.java:184)
    at com.redskyit.apns.processors.NotificatonProcessor.process(NotificatonProcessor.java:203)
    at com.redskyit.server.Server.process(Server.java:58)
    at com.redskyit.server.Server.run(Server.java:38)
    at com.redskyit.apns.apns.main(apns.java:41)

_Original issue: http://code.google.com/p/javapns/issues/detail?id=51_

**Comment by mwkirk** [comment]
_From idb...@pugetworks.com on May 24, 2011 21:32:15_
Just to verify... you are asking that the Device Token length be checked when the Token is passed to the Device object?

Added to 1.6.8

**Comment by mwkirk** [comment]
_From Austin.France on May 24, 2011 23:13:03_
Yes and Thanks

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 07, 2011 15:59:11_
Even though the javapns.data.Device (1.x) and javapns.devices.implementations.basic.BasicDevice (2.0) constructors do validate the token format, it is possible to pass a custom implementation of Device which would bypass the constructor-level validation.

I have improved the token validation in the 2.0 branch so that PushNotificationManager always validates the token in sendNotification(...).  The fix will be in my next commit.
