### ISSUE TITLE
stuck on pushManager.sendNotification( client, aPayload ); 

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#58]
_Original author: sguerr...@gmail.com (July 23, 2011 20:51:27)_

<b>What steps will reproduce the problem?</b>
1. Everytime I try to send a notification

<b>What is the expected output? What do you see instead?</b>
Expected to send a notification to ipod/iphone? 

Get the following error:
Connection initialized...
Attempt failed... trying again
preclose
in finally
java.net.SocketException: Socket is closed
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.checkEOF(Unknown Source)
    at com.sun.net.ssl.internal.ssl.AppInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at ts.javapns.back.PushNotificationManager.sendNotification(PushNotificationManager.java:199)
    at org.apache.jsp.japnslist_jsp._jspService(org.apache.jsp.japnslist_jsp:118)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:322)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:291)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:241)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:744)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Unknown Source)

<b>What version of the product are you using? On what operating system?</b>
Windows XP, newest version of javaapns

<b>Please provide any additional information below.</b>
 // APNs Server Host &amp; port  
 String HOST = &quot;gateway.sandbox.push.apple.com&quot;;  
 int PORT = 2195;  
 // Badge  
 int BADGE = 6;  
 // iPhone's UDID (64-char device token)  
 String iPhoneId = &quot;aebf53cc8d6bfaf47dace40747091fa5b0fc837b...&quot;;      

 String certificate = &quot;C:/webapplication/WEB-INF/cert.p12&quot;;  
 String passwd = &quot;password&quot;;  

 System.out.println( &quot;Setting up Push notification&quot; ); 

 //Set system properties .....
 System.setProperty(&quot;javax.net.ssl.trustStore&quot;, &quot;/var/www/apns/&lt;apple.keystore&gt;&quot;); 

 System.setProperty(&quot;javax.net.ssl.trustStorePassword&quot;, &quot;&lt;pass&gt;&quot;); 

try {  
  // Setup up a simple message  
  PayLoad aPayload = new PayLoad();  
  aPayload.addBadge( BADGE );  
  System.out.println( &quot;Payload setup successfull.&quot; );  
  System.out.println ( aPayload );              

  // Get PushNotification Instance  
  PushNotificationManager pushManager = PushNotificationManager.getInstance();       

  System.out.println( &quot;Linking iPhone's UDID (64-char device token) to a stringName&quot; );  

  // Link iPhone's UDID (64-char device token) to a stringName  
  pushManager.addDevice(&quot;iPhone&quot;, iPhoneId);  
  System.out.println( &quot;iPhone UDID taken.&quot; );  
  System.out.println( &quot;Token: &quot; + pushManager.getDevice( &quot;iPhone&quot; ).getToken() );              

  // Get iPhone client  
  Device client = pushManager.getDevice( &quot;iPhone&quot; );  
  System.out.println( &quot;Client setup successfull.&quot; );     

  // Initialize connection  
  pushManager.initializeConnection( HOST, PORT, certificate, passwd, SSLConnectionHelper.KEYSTORE_TYPE_PKCS12);  
  System.out.println( &quot;Connection initialized...&quot; );        

  // Send message  
  pushManager.sendNotification( client, aPayload );  
  System.out.println( &quot;Message sent!&quot; ); 

```
//Remove device
```

  pushManager.removeDevice(iPhoneId); 
  System.out.println( &quot;Removing Device&quot; );

  System.out.println( &quot;# of attempts: &quot; + pushManager.getRetryAttempts() );  
  pushManager.stopConnection();  
  System.out.println( &quot;done&quot; );  
} catch (Exception e) {  
  e.printStackTrace();  
} 

Please help.

_Original issue: http://code.google.com/p/javapns/issues/detail?id=58_

**Comment by mwkirk** [comment]
_From sguerr...@gmail.com on July 23, 2011 21:56:59_
As far as I can tell I am having an issue at this point in PushNotificationManager.java file

Function:
public void sendNotification(Device device, PayLoad payload) 

at this line of sendNotification:
this.socket.getOutputStream().write(getMessage(device.getToken(), new PayLoad() ));

Socket is closed but I do not know why it would be?

**Comment by mwkirk** [comment]
_From idbill.p...@gmail.com on July 25, 2011 21:36:27_
seems like a bad cert

what does the ssl debugging show?

**Comment by mwkirk** [comment]
_From sguerr...@gmail.com on July 28, 2011 12:19:02_
Thanks idbill... I finally got ti to work! and again sorry for sending you an email out of the blue... but thanks again!
