### ISSUE TITLE
Client already exists

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#65]
_Original author: franklin...@gmail.com (September 04, 2011 13:01:35)_

Client already exists
at javapns.back.DeviceFactory.addDevice(DeviceFactory.java:68)
at javapns.back.PushNotificationManager.addDevice(PushNotificationManager.java:132)
at com.shci.shms.materialmanagement.spring.controller.TCPushNotificationController.Push(TCPushNotificationController.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:445)
at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:383)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:858)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:792)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:476)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:441)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at com.shci.shms.common.filter.TCFilter.doFilter(TCFilter.java:76)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:179)
at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:84)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:241)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:580)
at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)

```
Actual Code
===========

    private static Logger log = Logger.getLogger(TCPushNotificationController.class);   


    private TCPushNotificationService tcPushNotificationService = null;


    // APNs Server Host &amp; port
    private static final String HOST = &quot;gateway.push.apple.com&quot;;
    private static final int PORT = 2195;


    // Badge
    private static final int BADGE = 66;


    // iPhone's UDID (64-char device token)
    //private static String iPhoneId = &quot;b92264f8f341db3fbb4255eb7a378bebc10f71c5fd9953d1c8129ee5d6ea817a&quot;;
    private static String certificate = &quot;c:/Certificates.p12&quot;;
    private static String passwd = &quot;12345&quot;;



    public ModelAndView Push(HttpServletRequest request, HttpServletResponse response) throws Exception {

        response.setHeader(&quot;Cache-Control&quot;, &quot;no-store&quot;);
        response.setHeader(&quot;Cache-Control&quot;, &quot;no-cache&quot;);
        response.setDateHeader(&quot;Expires&quot;, 0);
        response.setHeader(&quot;Pragma&quot;, &quot;no-cache&quot;);   
        request.setCharacterEncoding(&quot;UTF-8&quot;);
        response.setCharacterEncoding(&quot;UTF-8&quot;);

        String iPhoneToken = (String) request.getParameter(&quot;iPhoneToken&quot;);    
        String status = (String) request.getParameter(&quot;status&quot;);      
        String iPhoneId = iPhoneToken;

        String msg = &quot;Order Status : &quot; + status;

        log.info( &quot;Setting up Push notification&quot; );


       try {
            // Setup up a simple message
            PayLoad aPayload = new PayLoad();
            //aPayload.addBadge( BADGE );

            //aPayload.addAlert(&quot;Franklin Alert Message #2&quot;);
            aPayload.addAlert(msg);            

            log.info( &quot;Payload setup successfull.&quot; );


            log.info ( &quot;~~~~~aPayload=&quot;+aPayload );


            // Get PushNotification Instance
            PushNotificationManager pushManager = PushNotificationManager.getInstance();


            // Link iPhone's UDID (64-char device token) to a stringName
            pushManager.addDevice(&quot;iPhone&quot;, iPhoneId);
            log.info( &quot;iPhone UDID taken.&quot; );


            log.info( &quot;Token: &quot; + pushManager.getDevice( &quot;iPhone&quot; ).getToken() );


            // Get iPhone client
            Device client = pushManager.getDevice( &quot;iPhone&quot; );
            log.info( &quot;Client setup successfull.&quot; );


            // Initialize connection
            pushManager.initializeConnection( HOST, PORT, certificate, passwd, SSLConnectionHelper.KEYSTORE_TYPE_PKCS12);

            log.info( &quot;Connection initialized...&quot; );

            //pushManager.setRetryAttempts(100);

            // Send message
            pushManager.sendNotification( client, aPayload );
            log.info( &quot;Message sent!&quot; );


            log.info( &quot;# of attempts: &quot; + pushManager.getRetryAttempts() );


            pushManager.stopConnection();
            //pushManager.removeDevice(iPhoneId);
            //PushNotificationManager.getInstance().removeDevice(iPhoneId);


            //pushManager = null;


            log.info( &quot;done&quot; );


        } catch (Exception e) {
            //e.printStackTrace();
            log.error(&quot;Exception Caught : &quot;, e);
        }

        return null;
    }
```

Os : Window XP
Jboss : 4.2.1 
Java JDK : 1.5.0

_Original issue: http://code.google.com/p/javapns/issues/detail?id=65_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on September 06, 2011 16:29:31_
Your code always adds devices with the same ID ("iPhone" in your case).  Thus if you call your Push method twice, you will indeed get a duplicate device exception (ie "Client already exists").

SOLUTION FOR JAVAPNS 1.x:  You should make sure that devices are added with unique IDs.  Using the device token as the ID is a good way of ensuring unique IDs:  pushManager.addDevice(iPhoneId, iPhoneId);    and then later:  Device client = pushManager.getDevice(iPhoneId);

SOLUTION FOR JAVAPNS 2.0:  In 2.0, there is no need to add and get devices when no persistence backend is required.  The simple "javapns.Push" class allows you to push notifications with a single line of code (see wiki).
