### ISSUE TITLE
Received fatal alert: certificate_revoked

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#81]
_Original author: cpvpnmob...@gmail.com (November 08, 2011 21:58:58)_

Hi All,

We are trying to send production push notification but we are geting Error &quot;certificate_revoked&quot; all the time.
We follow the appropriate recommendations on your site( http://code.google.com/p/javapns/wiki/GetAPNSCertificate ) to making p12 file and we created p12 file for production and for development version.
In case of development version all works fine but when we are trying to use production version we got error below.

javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_revoked
      at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:174)
      at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:136)
      at com.sun.net.ssl.internal.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1720)
      at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
      at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1138)
      at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:632)
      at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:59)
      at java.io.OutputStream.write(OutputStream.java:58)
      at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:352)
      at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:301)
      at javapns.notification.PushNotificationManager.sendNotification(PushNotificationManager.java:258)
      at javapns.Push.payload(Push.java:122)
      at javapns.Push.combined(Push.java:83)
      at com.checkpoint.sgc.utils.PushTest.main(PushTest.java:12)

BTW, we have simple APN provider application on the MAC called &quot;PushMeBaby&quot; and it is working fine for both production and development versions.  

We checked several times that both applications use same development certificate and the same production certificate.

Any ideas what we doing wrong?

_Original issue: http://code.google.com/p/javapns/issues/detail?id=81_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on November 08, 2011 22:02:45_
Could you enable SSL debug (see Troubleshooting page) and copy-paste result please?

**Comment by mwkirk** [comment]
_From sype...@gmail.com on November 11, 2011 03:41:06_
Where you able to find a solution to this problem?

As far as I've been able to see on the web, a certificate_revoked error means pretty much what it says:  that Apple revoked your production certificate.  The solution seems to be to generate a new one.

Since the error is generated by Java's SSL implementation and not JavaPNS, and since the error appears to be self-explanatory, I would be tempted to close this issue as unrelated to the library itself.  Please write back (along with a SSL debug output) if you believe otherwise.  Thank you!

**Comment by mwkirk** [comment]
_From sype...@gmail.com on November 15, 2011 01:06:18_
Closing for lack of feedback.  Please feel free to re-open if you can provide the requested information and still believe the library is the cause.
