### ISSUE TITLE
Occasional ArrayIndexOutOfBoundsException in queue when all threads are busy

### ISSUE THREAD

**Issue by mwkirk** [mwkirk/javapns#85]
_Original author: gonz...@gmail.com (November 22, 2011 16:52:56)_

<b>What steps will reproduce the problem?</b>
Same as issue 84

<b>What version of the product are you using? On what operating system?</b>
2.1.1 stable

<b>Please provide any additional information below.</b>

I re-post my comment: 

Hi! I was wrong on the correction. The problem was when all of the threads were busy. 
This fixed the code:

protected NotificationThread getNextAvailableThread() {
        for (int i = 0; i &lt; threads.size(); i++) {
            NotificationThread thread = getNextThread();
            boolean busy = thread.isBusy();
            if (!busy) return thread;
        }
        return getNextThread(); /\* All threads are busy, return the next one regardless of its busy status */
    }

```
/**
 * Get the next thread to use.
 * 
 * @return a thread
 */
protected NotificationThread getNextThread() {
    if (nextThread &gt;= threads.size()) nextThread = 0;
    NotificationThread thread = threads.get(nextThread++);
    return thread;
}
```

_Original issue: http://code.google.com/p/javapns/issues/detail?id=85_

**Comment by mwkirk** [comment]
_From sype...@gmail.com on November 22, 2011 20:47:12_
Fixed in r338 (2.1.001).

**Comment by mwkirk** [comment]
_From Eventl...@gmail.com on January 16, 2012 23:24:30_
Judging from the original post, this issue still exists in 2.1.1?

**Comment by mwkirk** [comment]
_From sype...@gmail.com on January 16, 2012 23:29:42_
Issue 85 states that it was fixed in r338.  Have you tried the latest build?

**Comment by mwkirk** [comment]
_From Eventl...@gmail.com on January 17, 2012 02:39:23_
I will try 2.1.1 when we are ready for the next server upgrade. Thanks for your help!

**Comment by mwkirk** [comment]
_From sype...@gmail.com on January 17, 2012 04:28:44_
Make sure you try the latest BUILD, not just the latest released version....  See the Requirements wiki page for info about nightly builds.

**Comment by mwkirk** [comment]
_From gregp...@gmail.com on February 25, 2013 02:58:48_
I'm running 2.2 and this is still happening:

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.remove(Vector.java:804)
        at javapns.notification.PushedNotifications.prepareAdd(PushedNotifications.java:103)
        at javapns.notification.PushedNotifications.addAll(PushedNotifications.java:94)
        at javapns.notification.transmission.NotificationThreads.getPushedNotifications(NotificationThreads.java:402)
        at ly.cel.server.APNsManager.handlePushErrors(APNsManager.java:389)
        at ly.cel.server.APNsManager.pushCellMessageToClient(APNsManager.java:326)
        at ly.cel.notify.APNsMessageQueueManager.processCellMessage(APNsMessageQueueManager.java:90)
        at ly.cel.notify.APNsMessageQueueManager.processNewMessage(APNsMessageQueueManager.java:78)
        at ly.cel.notify.APNsMessageQueueManager.processNewMessage(APNsMessageQueueManager.java:28)
        at ly.cel.notify.HashedQueueManager.parseJSONAndExecute(HashedQueueManager.java:100)
        at ly.cel.notify.HashedQueueManager$HashedQueueConsumer.handleJSON(HashedQueueManager.java:120)
        at com.p2.alchemy.JSONConsumer$1.doTake(JSONConsumer.java:107)
        at com.p2.alchemy.JSONConsumer$1.run(JSONConsumer.java:56)
        at java.lang.Thread.run(Thread.java:679)
